SELECT ITEM_ID, ITEM_NAME
FROM ITEM_INFO I
WHERE ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NULL
)
ORDER BY ITEM_ID






# SELECT I.ITEM_ID, I.ITEM_NAME
# FROM ITEM_TREE T
# JOIN ITEM_INFO I
# ON I.ITEM_ID = T.ITEM_ID
# WHERE T.PARENT_ITEM_ID IS NULL
# ORDER BY I.ITEM_ID

# ROOT 아이템의 PARENT 아이템 ID는 NULL 
# ROOT 아이템을 찾아 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME)을 출력
# 이때, 결과는 아이템 ID를 기준으로 오름차순 정렬