SELECT C.ID
FROM ECOLI_DATA G
JOIN ECOLI_DATA P
    ON G.PARENT_ID IS NULL AND G.ID = P.PARENT_ID
JOIN ECOLI_DATA C
    ON P.ID = C.PARENT_ID
ORDER BY C.ID










# WITH RECURSIVE RCTE AS (
#     SELECT ID, 1 AS GENERATION
#     FROM ECOLI_DATA
#     WHERE PARENT_ID IS NULL
    
#     UNION ALL
    
#     SELECT E.ID, R.GENERATION + 1 AS GENERATION
#     FROM ECOLI_DATA E
#     JOIN RCTE R
#     ON E.PARENT_ID = R.ID
# )

# SELECT ID
# FROM RCTE
# WHERE GENERATION = 3
# ORDER BY ID