SELECT F.USER_ID, F.PRODUCT_ID
FROM ONLINE_SALE F
JOIN ONLINE_SALE S
    ON F.USER_ID = S.USER_ID 
    AND F.ONLINE_SALE_ID != S.ONLINE_SALE_ID 
    AND F.PRODUCT_ID = S.PRODUCT_ID
GROUP BY F.USER_ID, F.PRODUCT_ID
ORDER BY F.USER_ID, F.PRODUCT_ID DESC








# SELECT USER_ID, PRODUCT_ID 
# FROM ONLINE_SALE
# GROUP BY USER_ID, PRODUCT_ID
# HAVING COUNT(*) >= 2
# ORDER BY USER_ID, PRODUCT_ID DESC