SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE * 30 * (1-P.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND P.DURATION_TYPE = '30일 이상'
AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC


# SELECT CAR_ID, CAR_TYPE, FEE
# FROM (
#     SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE)/100) AS FEE
#     FROM CAR_RENTAL_COMPANY_CAR C
#     JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
#     ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
#     GROUP BY C.CAR_ID, C.CAR_TYPE
# ) F
# WHERE CAR_TYPE IN ('세단', 'SUV')
# AND CAR_ID NOT IN ( # 한번이라도 11월달에 빌린 기록이 있다면 불포함
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE < '2022-12-01' AND END_DATE > '2022-10-31'
# )
# AND FEE >= 500000 && FEE < 2000000
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC