WITH RANKED AS (
    SELECT
        ID,
        (SELECT COUNT(*) FROM ECOLI_DATA) AS TOTAL_COUNT,
        RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKED
    FROM ECOLI_DATA
)

SELECT 
    ID,
    CASE
        WHEN RANKED <= TOTAL_COUNT * 0.25 THEN 'CRITICAL'
        WHEN RANKED <= TOTAL_COUNT * 0.5 THEN 'HIGH'
        WHEN RANKED <= TOTAL_COUNT * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM RANKED
ORDER BY ID
