SELECT 
    E.ID,
    CASE
        WHEN R.RNK / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.25 THEN 'CRITICAL'
        WHEN R.RNK / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.5 THEN 'HIGH'
        WHEN R.RNK / (SELECT COUNT(*) FROM ECOLI_DATA) <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA E
JOIN (
    SELECT S.ID, COUNT(B.ID) AS RNK
    FROM ECOLI_DATA B
    JOIN ECOLI_DATA S
        ON B.SIZE_OF_COLONY >= S.SIZE_OF_COLONY
    GROUP BY S.ID
) AS R
    ON E.ID = R.ID
ORDER BY E.ID










# SELECT ID,
#     CASE
#         WHEN P_RANK <= 0.25 THEN 'CRITICAL'
#         WHEN P_RANK <= 0.5 THEN 'HIGH'
#         WHEN P_RANK <= 0.75 THEN 'MEDIUM'
#         ELSE 'LOW'
#     END AS COLONY_NAME
# FROM (
#     SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS P_RANK
#     FROM ECOLI_DATA
# ) AS SUB
# ORDER BY ID