SELECT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID AND U.GENDER IS NOT NULL
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER
ORDER BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER






# SELECT 
#     YEAR(S.SALES_DATE) YEAR, 
#     MONTH(S.SALES_DATE) MONTH, 
#     U.GENDER, 
#     COUNT(DISTINCT U.USER_ID) USERS
# FROM USER_INFO U
# JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
# WHERE U.GENDER IS NOT NULL
# GROUP BY YEAR, MONTH, U.GENDER
# ORDER BY YEAR, MONTH, U.GENDER