SELECT
ANIMAL_TYPE,
COUNT(ANIMAL_TYPE) AS 'count'
FROM ANIMAL_INS 
WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
GROUP BY ANIMAL_TYPE
ORDER BY
    CASE
        WHEN ANIMAL_TYPE = 'Cat' THEN 0
        WHEN ANIMAL_TYPE = 'Dog' THEN 1
    END
    , ANIMAL_TYPE