WITH EVERY_USER AS (
    SELECT COUNT(*) AS COUNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT 
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT U.USER_ID)/E.COUNT, 1) AS PUCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID
CROSS JOIN EVERY_USER E

WHERE YEAR(U.JOINED) = 2021

GROUP BY YEAR, MONTH, E.COUNT
ORDER BY YEAR, MONTH