# SELECT COUNT(U.USER_ID)
# FROM (
#     SELECT *
#     FROM USER_INFO
#     WHERE YEAR(JOINED) = '2021'
# ) U
# LEFT JOIN ONLINE_SALE O
#     ON U.USER_ID = O.USER_ID
# GROUP BY U.USER_ID AND 

SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT O.USER_ID)/(
    SELECT COUNT(USER_ID)
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
), 1) AS PURCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED) = '2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH



# SELECT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, COUNT(DISTINCT U.USER_ID) PURCHASED_USERS, ROUND(COUNT(DISTINCT U.USER_ID)/ (
#     SELECT COUNT(*)
#     FROM USER_INFO 
#     WHERE YEAR(JOINED) = '2021'
# ), 1) AS PURCHASED_RATIO
# FROM USER_INFO U
# JOIN ONLINE_SALE S
# ON U.USER_ID = S.USER_ID
# WHERE YEAR(U.JOINED) = '2021'
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH