WITH RECURSIVE GENERATION_CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E1.ID, E1.PARENT_ID, GC.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E1
    JOIN GENERATION_CTE GC ON E1.PARENT_ID = GC.ID
)

SELECT 
    COUNT(*) AS COUNT,
    GC.GENERATION
FROM GENERATION_CTE GC
LEFT JOIN ECOLI_DATA E1 ON GC.ID = E1.PARENT_ID
WHERE E1.ID IS NULL
GROUP BY GC.GENERATION
ORDER BY GC.GENERATION