WITH RECURSIVE RCTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, R.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN RCTE R
        ON E.PARENT_ID = R.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM RCTE
WHERE ID NOT IN (
    SELECT P.ID
    FROM ECOLI_DATA P
    JOIN ECOLI_DATA C
        ON P.ID = C.PARENT_ID
    GROUP BY P.ID
)
GROUP BY GENERATION
ORDER BY GENERATION







# WITH RECURSIVE RCTE AS (
#     SELECT ID, 1 AS GENERATION
#     FROM ECOLI_DATA
#     WHERE PARENT_ID IS NULL
    
#     UNION ALL

#     SELECT E.ID, R.GENERATION + 1 AS GENERATION
#     FROM ECOLI_DATA E
#     JOIN RCTE R
#     ON E.PARENT_ID = R.ID
# )

# SELECT COUNT(*) AS COUNT, R.GENERATION
# FROM ECOLI_DATA P
# LEFT JOIN ECOLI_DATA C
# ON C.PARENT_ID = P.ID
# JOIN RCTE R
# ON P.ID = R.ID
# WHERE C.ID IS NULL
# GROUP BY R.GENERATION
# ORDER BY R.GENERATION