WITH AVAILABLE AS (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 

WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16')

SELECT
    C.CAR_ID,
    IF(A.CAR_ID IS NULL, '대여 가능', '대여중') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
LEFT JOIN AVAILABLE A
ON C.CAR_ID = A.CAR_ID

GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC