SELECT 
    H.HISTORY_ID,
    ROUND(C.DAILY_FEE * H.DATENUM * (1 - IFNULL(P.DISCOUNT_RATE, 0)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT HISTORY_ID, CAR_ID, (DATEDIFF(END_DATE, START_DATE) + 1) AS DATENUM
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
) H
ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = (
            CASE
                WHEN H.DATENUM >= 90 THEN '90일 이상'
                WHEN H.DATENUM >= 30 THEN '30일 이상'
                WHEN H.DATENUM >= 7 THEN '7일 이상'
            END
        )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC







# SELECT H.HISTORY_ID,
#     ROUND((DATEDIFF(H.END_DATE, H.START_DATE)+1) * C.DAILY_FEE * (1 - IFNULL(P.DISCOUNT_RATE, 0)/100)) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR C
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# ON C.CAR_ID = H.CAR_ID
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
# ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = (
#     CASE
#         WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1) >= 90 THEN '90일 이상'
#         WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1) >= 30 THEN '30일 이상'
#         WHEN (DATEDIFF(H.END_DATE, H.START_DATE)+1) >= 7 THEN '7일 이상'
#     END
# )
# WHERE C.CAR_TYPE = '트럭'
# ORDER BY FEE DESC, H.HISTORY_ID DESC