SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
JOIN PATIENT P
ON A.PT_NO = P.PT_NO
WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD







# SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
# FROM APPOINTMENT A
# JOIN PATIENT P
# ON A.PT_NO = P.PT_NO
# JOIN DOCTOR D
# ON D.DR_ID = A.MDDR_ID
# WHERE D.MCDP_CD = 'CS' 
#     AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
#     AND APNT_CNCL_YN = 'N'
# ORDER BY A.APNT_YMD
# 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역 조회
# 진료예약번호APNT_NO, 환자이름PT_NAME, 환자번호PT_NO, 진료과코드MCDP_CD, 의사이름DR_NAME, 진료예약일시APNT_YMD
# 진료예약일시 기준으로 오름차순 정렬