WITH RECURSIVE RCTE AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1 AS HOUR
    FROM RCTE
    WHERE HOUR < 23
)

SELECT R.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM RCTE R
LEFT JOIN ANIMAL_OUTS A
ON R.HOUR = HOUR(A.DATETIME)
GROUP BY R.HOUR
ORDER BY R.HOUR



# WITH RECURSIVE RCTE AS (
#     SELECT 0 AS HOUR
#     UNION ALL
#     SELECT HOUR + 1 AS HOUR FROM RCTE WHERE HOUR < 23
# )

# SELECT R.HOUR AS HOUR, COUNT(O.ANIMAL_ID) AS COUNT
# FROM RCTE R
# LEFT JOIN ANIMAL_OUTS O
# ON R.HOUR = HOUR(O.DATETIME)
# GROUP BY R.HOUR
# ORDER BY R.HOUR