SELECT C.ID, C.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA C
JOIN ECOLI_DATA P
    ON P.ID = C.PARENT_ID
WHERE P.GENOTYPE & C.GENOTYPE = P.GENOTYPE
ORDER BY C.ID








# SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE
# FROM ECOLI_DATA AS A
# JOIN ECOLI_DATA AS B
# ON A.PARENT_ID = B.ID
# WHERE A.GENOTYPE & B.GENOTYPE = B.GENOTYPE
# ORDER BY A.ID