SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME






# SELECT I.ANIMAL_ID, I.NAME
# FROM ANIMAL_INS I
# JOIN ANIMAL_OUTS O
# ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.DATETIME > O.DATETIME
# ORDER BY I.DATETIME

# 보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름을 조회
# 이때 결과는 보호 시작일이 빠른 순으로 조회