SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE NAME IN ('C#', 'Python')
) > 0
ORDER BY ID







# SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
# FROM DEVELOPERS AS D
# JOIN (
#     SELECT SUM(CODE) AS SCODE
#     FROM SKILLCODES
#     WHERE NAME = 'Python' OR NAME = 'C#'
# ) AS S
# ON D.SKILL_CODE & S.SCODE > 0
# ORDER BY D.ID