SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA 
ORDER BY YEAR, YEAR_DEV







# SELECT 
#     YEAR(E.DIFFERENTIATION_DATE) AS YEAR, 
#     T.MAX - E.SIZE_OF_COLONY AS YEAR_DEV,
#     ID
# FROM ECOLI_DATA E
# JOIN (
#     SELECT 
#         YEAR(DIFFERENTIATION_DATE) AS YEAR, 
#         MAX(SIZE_OF_COLONY) AS MAX
#     FROM ECOLI_DATA
#     GROUP BY YEAR(DIFFERENTIATION_DATE)
# ) T
#     ON YEAR(E.DIFFERENTIATION_DATE) = T.YEAR
# ORDER BY YEAR(E.DIFFERENTIATION_DATE), T.MAX - E.SIZE_OF_COLONY




# WITH MAX_TABLE AS (
#     SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
#         MAX(SIZE_OF_COLONY) AS MAX_SIZE
#     FROM ECOLI_DATA
#     GROUP BY YEAR(DIFFERENTIATION_DATE)
# )

# SELECT MT.YEAR, 
#     MT.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV, 
#     E.ID
# FROM ECOLI_DATA E
# JOIN MAX_TABLE MT
# ON MT.YEAR = YEAR(E.DIFFERENTIATION_DATE)
# ORDER BY MT.YEAR, YEAR_DEV