SELECT
I.ID AS ID,
N.FISH_NAME AS FISH_NAME,
IF(LENGTH <= 10, NULL, LENGTH) AS LENGTH
FROM FISH_INFO AS I
JOIN FISH_NAME_INFO AS N
ON I.FISH_TYPE = N.FISH_TYPE
WHERE 
LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO AS I2
    WHERE I.FISH_TYPE = I2.FISH_TYPE
)
ORDER BY I.ID