SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC










# SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT 
# WHERE CATEGORY IN ('과자','국','김치','식용유')
#     AND (CATEGORY, PRICE) IN (
#         SELECT CATEGORY, MAX(PRICE) MAX_PRICE
#         FROM FOOD_PRODUCT
#         GROUP BY CATEGORY
#     )
# ORDER BY PRICE DESC